# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Web App repo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "webapp"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Viewer
        uses: actions/checkout@v4
        with:
          path: viewer
      - name: Checkout Web App
        uses: actions/checkout@v4
        with:
          repository: BrainStimulation/optical-irradiance-contour-webapp
          path: webapp
          token: ${{ secrets.PUSH_WEB_APP_TOKEN }}
      - name: Install libarchive-dev and libcurl4-openssl-dev
        run: sudo apt-get install -y libarchive-dev libcurl4-openssl-dev
      - name: Set up r2u
        run: |
          sudo apt-get update -qq
          sudo apt-get install --no-install-recommends software-properties-common dirmngr
          wget -q -O- https://eddelbuettel.github.io/r2u/assets/dirk_eddelbuettel_key.asc | sudo tee -a /etc/apt/trusted.gpg.d/cranapt_key.asc
          echo "deb [arch=amd64] https://r2u.stat.illinois.edu/ubuntu noble main" | sudo tee /etc/apt/sources.list.d/cranapt.list
          sudo apt-get update
          sudo apt-get install --no-install-recommends r-base r-cran-tidyverse
      - name: Install dependencies
        shell: bash
        run: |
          # sudo apt update && sudo apt install r-base r-base-dev -y
          sudo /usr/bin/Rscript viewer/src/install.R
          sudo /usr/bin/Rscript --version
      - name: Clean destination
        shell: bash
        run: |
          # Clean out the old files from the webapp repo, but NOT the .git folder
          find webapp -mindepth 1 -not -path 'webapp/.git*' -delete
      - name: Build web application
        shell: Rscript {0}
        run: |
          shinylive::assets_version()
          shinylive::export(appdir = "viewer/src", destdir = "webapp", assets_version = "0.10.6")
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "actions"
      - name: Add data files
        shell: bash
        run: |
          mkdir -p webapp/data
          curl -X GET -L "https://api.figshare.com/v2/file/download/46963453" --output webapp/data/grey.mat -s &
          curl -X GET -L "https://api.figshare.com/v2/file/download/46963456" --output webapp/data/white.mat -s &
          wait
      - name: Commit changes and push to website
        shell: bash
        run: |
          cd webapp
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Latest changes for web application."
            git push origin main
          fi    
